######################################################################
# Automatically generated by qmake (3.1) Sun Apr 2 17:21:03 2023
######################################################################

TEMPLATE = app
TARGET = AGL_Quiz_Application
INCLUDEPATH += .

QT += gui widgets

DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += AGL_Quiz_Application.cpp

target.path = /usr/bin
target.files += $${OUT_PWD}/$${TARGET}
target.CONFIG = no_check_exist executable

INSTALLS += target
